name: "verify module modified"
description: "given a list of modules, verifies which ones need to be tagged"
inputs:
  modules:
    description: "list of modules to verify"
    required: true
outputs:
  modules:
    description: "list of modules that were modified on this commit separated by space"
    value: ${{ steps.modified_modules.outputs.modules }}
runs:
  using: composite
  steps:
    - shell: bash
      id: modified_modules
      run: |
        m=( ${{ inputs.modules }} )
        
        base=$(jq -r .before ${GITHUB_EVENT_PATH})
        head=$(jq -r .after ${GITHUB_EVENT_PATH})
        folders=(`git diff --name-only ${base}...${head} | rev | cut -d/ -f2- | rev | sort -u `)
        
        modified_modules=()
        for mod in ${m[@]}
        do
          for f in ${folders[@]}
          do
            if [ "$f" == "$mod" ]; then
              modified_modules+=("$f")
            fi
          done
        done
        
        echo "::set-output name=modules::${modified_modules[@]}"