name: tag-release
on:
  push:
    branches:
      - main
    paths:
      - client/*
      - proto/*
      - service/*
      - deep/**
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: release changed
    steps:
      - uses: actions/checkout@v3
        name: checkout
        with:
          # non-shallow, because we want tag information
          fetch-depth: 0
      - uses: ./.github/actions/tag-versions/compute-modules
        name: get modules
        id: folders
      - uses: ./.github/actions/tag-versions/was-module-modified
        name: check modified
        id: modified
        with:
          modules: ${{ steps.folders.outputs.modules }}
      - uses: ./.github/actions/tag-versions/get-current-versions
        name: get current versions
        id: versions
        with:
          modules: ${{ steps.modified.outputs.modules }}
      - uses: ./.github/actions/tag-versions/upgrade-module-versions
        name: upgrade versions
        id: upg-versions
        with:
          jsonTag: ${{ steps.versions.outputs.jsonTag }}
      - uses: ./.github/actions/tag-versions/tag-and-push-versions
        name: tag and push versions
        id: tag-n-push
        with:
          jsonTag: ${{ steps.upg-versions.outputs.jsonTag }}
