name: tag-release
on:
  push:
    branches:
      - main
jobs:
  test-n-tag:
    outputs:
      newTags: ${{ steps.matrix-output.outputs.matrix }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: release changed
    steps:
      - uses: actions/checkout@v3
        name: checkout
        with:
          # non-shallow, because we want tag information
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: ./.github/actions/tag-versions/compute-modules
        name: get modules
        id: folders
      - uses: ./.github/actions/tag-versions/was-module-modified
        name: check modified
        id: modified
        with:
          modules: ${{ steps.folders.outputs.modules }}
      - name: modified modules
        env: { MODULES_OUTPUT: "${{ toJson(steps.modified.outputs) }}" }
        run: "echo $MODULES_OUTPUT"
      - name: Run Test
        if: ${{ fromJSON(steps.modified.outputs.modified) }}
        shell: bash
        run: |
          m=( ${{ steps.modified.outputs.modules }} )
          printf "%s\n" ${m[@]} | xargs -I{} go test ./{}/...
      - uses: ./.github/actions/tag-versions/get-current-versions
        if: ${{ fromJSON(steps.modified.outputs.modified) }}
        name: get current versions
        id: versions
        with:
          modules: ${{ steps.modified.outputs.modules }}
      - uses: ./.github/actions/tag-versions/upgrade-module-versions
        if: ${{ fromJSON(steps.modified.outputs.modified) }}
        name: upgrade versions
        id: upg-versions
        with:
          jsonTag: ${{ steps.versions.outputs.jsonTag }}
      - uses: ./.github/actions/tag-versions/tag-and-push-versions
        if: ${{ fromJSON(steps.modified.outputs.modified) && !env.ACT }}
        name: tag and push versions
        id: tag-n-push
        with:
          jsonTag: ${{ steps.upg-versions.outputs.jsonTag }}
      - name: convert jsonTags to array of pairs
        if: ${{ fromJSON(steps.modified.outputs.modified) }}
        id: matrix-output
        shell: bash
        run: |
          echo ${{ steps.upg-versions.outputs.jsonTag }}
          jsonTag=${{ steps.upg-versions.outputs.jsonTag }}
          echo $jsonTag
          inline=$(echo $jsonTag | jq -c 'to_entries | map( {"module": "\(.key)", "version": "\(.value)"}) | {"include": .}')
          echo $inline
          echo "::set-output name=matrix::$inline"
  check-matrix:
    runs-on: ubuntu-latest
    needs: [test-n-tag]
    steps:
      - name: Install json2yaml
        run: |
          npm install -g json2yaml

      - name: Check matrix definition
        run: |
          matrix='${{ needs.test-n-tag.outputs.newTags }}'
          echo $matrix
          echo $matrix | jq .
          echo $matrix | json2yaml
  build-new-binaries:
    runs-on: ubuntu-latest
    needs: [test-n-tag]
    strategy:
      matrix: ${{ fromJson(needs.test-n-tag.outputs.newTags) }}
    steps:
      - name: "debug"
        shell: bash
        run: |
          echo ${{ needs.test-n-tag.outputs.newTags }}
          echo "matrix ${{ toJSON(matrix) }}"
          echo ${{ matrix.module }}
          echo ${{ matrix.version }}
      - uses: actions/checkout@v3
        name: checkout
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: build_changed
        env:
          GOAMD64: v3
        shell: bash
        run: |
          mkdir -p bin
          go build -o ./bin/${{ matrix.module }} ./${{ matrix.module }}
          rm -rf bin
