name: tag-release
on:
  push:
    branches:
      - main
    paths:
      - client/*
      - proto/*
      - service/*
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    name: release changed
    steps:
      - uses: actions/github-script@v6
        name: check if should release
        id: folders
        with:
          result-encoding: json
          script: |
            const RELEVANT_PATHS = new Map([
                ["client", false],
                ["proto", false],
                ["service", false],
            ]);
            const diff = await github.rest.repos.compareCommitsWithBasehead({
                owner: context.repo.owner,
                repo: context.repo.repo,
                basehead: `${context.payload.before}...${context.payload.after}`,
            });
            if (!diff.status || diff.status > 299) {
                return []
            }
            const filesChanged = diff.data.files.map((f) => f.filename);
            core.info("Files changed since last push: " + JSON.stringify(filesChanged));
            for (let [path, _] of RELEVANT_PATHS) {
                if (filesChanged.some((f) => f.startsWith(path + "/"))) {
                    RELEVANT_PATHS.set(path, true);
                }
            }
            const result = [...RELEVANT_PATHS].filter(([_, v]) => v).map(([k, _]) => k);
            core.info("Modules to be released: " + JSON.stringify(result));
            return result;
      - uses: actions/checkout@v3
        name: checkout
        with:
          # non-shallow, because we want tag information
          fetch-depth: 0
      - run: npm install semver
      - uses: actions/github-script@v6
        name: get latest tags for new releases
        id: versions
        with:
          script: |
            const folders = ${{ steps.folders.outputs.result }} ;
            //
            const currentVersions = new Map();
            for (let module of folders) {
                let resultTag = await (
                    exec.getExecOutput("git", ["tag", "-l", `${module}/*`, "--sort", "-v:refname"], {silent: true})
                        .then(output => output.stdout.split("\n")[0])
                );
                if (!resultTag) {
                    resultTag = `${module}/v0.0.1`;
                }
                core.info("found tag " + resultTag)
                currentVersions.set(module, resultTag);
            }
            const semver = require('semver');
            const newVersions = new Map();
            for (let [module, tag] of currentVersions) {
                let cleanVersion = semver.valid(tag.split('/')[1])
                if (!cleanVersion) {
                    cleanVersion = "0.0.0"
                }
                let incVersion = semver.inc(cleanVersion, 'patch')
                newVersions.set(module, `${module}/v${incVersion}`)
            }
            const result = [...newVersions.values()]
            core.info("New tags will be " + result)
            return result
      - uses: fregante/setup-git-user@v1
      - uses: actions/github-script@v6
        name: tag versions and push
        with:
          script: |
            const tags = ${{ steps.versions.outputs.result }} ;
            //
            let cmds = []
            for (let tag of tags) {
                cmds.push(`git tag -a ${tag} -m "${tag}"`)
            }
            cmds.push(`git push origin --tags ${process.env.GITHUB_SHA}:${process.env.GITHUB_REF}`)
            let results = await Promise.all(cmds.map(cmd => exec.exec(cmd)))
            core.info("tags pushed. Exit codes: " + results)
